version: "3.8"

services:

  registry:
    image: registry-image
    build: ./registry
    ports:
      - "5000:5000"
    networks:
      - bully-net

  node:
    image: node-image
    build: ./node
    deploy:
      replicas: 4
    networks:
      - bully-net

networks:
  bully-net:
    external: true